### ISSUE TITLE
长时间运行会出现 attempted to read or write protected memory

### ISSUE THREAD

**Issue by heartacker** [HandyOrg/HandyIpc#21]
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Threading.ThreadPoolWorkQueue.TryDequeueTimeSensitiveWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dequeue(System.Threading.ThreadPoolWorkQueueThreadLocals, Boolean ByRef)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```

**Comment by DingpingZhang** [comment]
`AccessViolationException` 不是托管异常，感觉是微软的 bug。要不你用最新的 .Net6.0 运行试试看？看看他们修复了没有。
如果 Task 不能用，我可能要自己做个消费者队列了，可能要一番改造，不是一时半会能搞好的。
你说的“长时间”是多长时间？发生的频率大约是多少？期间 API 的调用频率如何？

**Comment by heartacker** [comment]
@DingpingZhang 顺便问问，这个也很常见，有什么好办法定位吗？
![image](https://user-images.githubusercontent.com/1876302/177366787-387439b0-c7d2-42b5-9704-0a971a7f731f.png)

**Comment by DingpingZhang** [comment]
@heartacker 这个你参考一下 #20

**Comment by heartacker** [comment]
> @heartacker 这个你参考一下 #20 

应该不是这个问题。那个问题已经修复了，我现在用的是同一套代码。我感觉可能不是这个问题

**Comment by DingpingZhang** [comment]
> > @heartacker 这个你参考一下 #20
> 
> 应该不是这个问题。那个问题已经修复了，我现在用的是同一套代码。我感觉可能不是这个问题

那你像上次一样，打一个断点，看看非法的 response data 是什么？

**Comment by heartacker** [comment]
> > > @heartacker 这个你参考一下 #20
> > 
> > 
> > 应该不是这个问题。那个问题已经修复了，我现在用的是同一套代码。我感觉可能不是这个问题
> 
> 那你像上次一样，打一个断点，看看非法的 response data 是什么？

上次是没有给你看到服务端的，这次我发现首先是服务端报错了。
![image](https://user-images.githubusercontent.com/1876302/177537706-0c2abae5-64f3-4ebd-b1be-63badcde58e0.png)

**Comment by heartacker** [comment]
> `AccessViolationException` 不是托管异常，感觉是微软的 bug。要不你用最新的 .Net6.0 运行试试看？看看他们修复了没有。 如果 Task 不能用，我可能要自己做个消费者队列了，可能要一番改造，不是一时半会能搞好的。 你说的“长时间”是多长时间？发生的频率大约是多少？期间 API 的调用频率如何？


我现在用的就是NET6，长时间可能半天就会如果client 多的时候表现的比较明显。
